trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - src
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables: 
- name: buildConfiguration
  value: 'Release'
- name: majorVersion
  value: 0
- name: minorVersion
  value: 1
- name: patchVersion
  value: 6
- group: 'Nuget sevantage'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)'
    projects: 'BillomatNet.sln'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    arguments: '--configuration $(buildConfiguration) --collect "XPlat Code Coverage" --filter Category=UnitTest'
    projects: '*Tests/*.csproj'
    nobuild: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'Develappers.BillomatNet/Develappers.BillomatNet.csproj'
    nobuild: true
    includesymbols: true
    majorVersion: $(majorVersion)
    minorVersion: $(minorVersion)
    patchVersion: $(patchVersion)
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      versioningScheme: off
    ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
      versioningScheme: byPrereleaseNumber    

# Publish only for dev & master
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
  
- task: DotNetCoreCLI@2
  displayName: 'dotnet nuget push'
  inputs:
    command: 'custom'
    custom: nuget
    arguments: >
      push $(Build.ArtifactStagingDirectory)/*.nupkg
      -s https://sevantage.pkgs.visualstudio.com/_packaging/sevantage/nuget/v3/index.json

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'package'
